import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="py-4 absolute top-0 z-50 w-full border-b border-white">
          Home | About | Contact
        </nav>
        {children}
        <footer>Quick Links</footer>
      </body>
    </html>
  );
}
